### ISSUE TITLE
How to enable full screen mode in on desktop ?

### ISSUE THREAD

**Issue by AionDev** [jamesjohnson280/hello-pwa#6]
In the `sw.js` file i changed this line: 
```
"display": "fullscreen",
```
But for some reason the app does not work in full screen when on desktop. 
Any ideas what I'm doing wrong?

**Comment by jamesjohnson280** [comment]
You need to uses the fullscreen api to do it. It won't just work out of the box. Check out the docs on MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

Hope that helps!
